spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    username: root
    password: xinyu2
    url: jdbc:mysql://192.168.145.128:3306/xinyu_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=PRC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    filters: stat
    logSlowSql: true
#  redis:
#    host:
#    port: 6379
#    password:
#    database: 0
#    timeout: 5000ms
#    pool:
#      lettuce:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0

server:
  tomcat:
    uri:
      encoding: UTF-8
  port: 8899

logging:
  config: classpath:logback-spring.xml
  path: ./logs

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开发环境开启sql日志输出
  #为了支持jsr310标准，注册其中时间类的类型转换器
  typeHandlersPackage: com.xinyu.simple.dao.handler
